/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        'paper-deep': 'var(--paper-deep)',
        sheet: 'var(--sheet)',
        'sheet-edge': 'var(--sheet-edge)',
        'sheet-edge-2': 'var(--sheet-edge-2)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        'ink-4': 'var(--ink-4)',
        hair: 'var(--hair)',
        'hair-soft': 'var(--hair-soft)',
        rule: 'var(--rule)',
        green: {
          50: 'var(--green-50)',
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
          800: 'var(--green-800)',
          900: 'var(--green-900)',
        },
        crit: 'var(--crit)',
        'crit-bg': 'var(--crit-bg)',
        'crit-edge': 'var(--crit-edge)',
        warn: 'var(--warn)',
        'warn-bg': 'var(--warn-bg)',
        'warn-edge': 'var(--warn-edge)',
        info: 'var(--info)',
        'info-bg': 'var(--info-bg)',
        'info-edge': 'var(--info-edge)',
        ok: 'var(--ok)',
        'ok-bg': 'var(--ok-bg)',
        'ok-edge': 'var(--ok-edge)',
      },
      fontFamily: {
        serif: ['Fraunces', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        sharp: '6px',
        soft: '12px',
        card: '16px',
        'card-lg': '20px',
        pill: '9999px',
      },
      transitionTimingFunction: {
        pracket: 'cubic-bezier(.4,0,.2,1)',
      },
      transitionDuration: {
        quick: '120ms',
        normal: '220ms',
        slow: '360ms',
      },
      boxShadow: {
        line: '0 0 0 1px var(--sheet-edge)',
        shade: '0 1px 0 rgba(31,35,28,0.04)',
        pop: '0 12px 32px -16px rgba(31,35,28,0.18), 0 2px 8px -4px rgba(31,35,28,0.08)',
        modal: '0 30px 60px -30px rgba(0,0,0,.35), 0 8px 24px -12px rgba(0,0,0,.18)',
        toast: '0 8px 24px -12px rgba(0,0,0,0.18)',
      },
      letterSpacing: {
        display: '-0.022em',
        h: '-0.014em',
        label: '0.01em',
        overline: '0.16em',
      },
    },
  },
  plugins: [],
}
