export * from './format-naira'
export * from './get-initials'
export * from './mask-name'
export * from './avatar-tone'
export * from './is-student'
export * from './is-tutor'
export * from './is-admin'
